#!/bin/sh
OLDPATH=$PATH
WHEREAMI=`pwd`

SCRIPTDIR="`dirname \"$0\"`"
EXAMPLES="`cd \"$SCRIPTDIR\" && pwd`"

export PATH="$EXAMPLES/../node_binaries/bin:$PATH"
NODEINST=`which node`

        # echo " [i] using node executable $NODEINST"
        node $@

export PATH="$OLDPATH"
cd "$WHEREAMI"
